### ISSUE TITLE
Uncaught Error on Adding New Feed

### ISSUE THREAD

**Issue by cogdog** [radgeek/feedwordpress#135]
I get a WordPress critical issue issue on adding a new feed, but the feed ends up in the syndication list and all feeds operate as usual.

The error reported is

```
An error of type E_ERROR was caused in line 1203 of the file /home/cogdog/public_html/cogdogblog.com/wp-content/plugins/feedwordpress/feedwordpresssyndicationpage.class.php. Error message: Uncaught Error: Using $this when not in object context in /home/cogdog/public_html/cogdogblog.com/wp-content/plugins/feedwordpress/feedwordpresssyndicationpage.class.php:1203
Stack trace:
#0 /home/cogdog/public_html/cogdogblog.com/wp-content/plugins/feedwordpress/feedwordpresssyndicationpage.class.php(409): fwp_switchfeed_page()
#1 /home/cogdog/public_html/cogdogblog.com/wp-content/plugins/feedwordpress/syndication.php(5): FeedWordPressSyndicationPage->display()
#2 /home/cogdog/public_html/cogdogblog.com/wp-admin/admin.php(293): include('/home/cogdog/pu...')
#3 {main}
```

running under:

```
WordPress version 5.8.3
Current plugin: FeedWordPress (version 2022.0208)
PHP version 7.4.9
```

_Originally posted in another issue by @cogdog in https://github.com/radgeek/feedwordpress/issues/134#issuecomment-1035314947_

**Comment by radgeek** [comment]
Thanks for this report, and sorry for the trouble.

I *think* that this issue should be resolved in the most recent round of code cleanups, now available as version 2022.0222 here via `git pull` (or on the WordPress Plugin Repository page). Could you take a look and see if bumping up to the latest version solves the problem for you?
